# Generated by Django 6.1 on 2026-08-24 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio_2000', models.IntegerField(blank=True, null=True)),
                ('anio_2001', models.IntegerField(blank=True, null=True)),
                ('anio_2002', models.IntegerField(blank=True, null=True)),
                ('anio_2003', models.IntegerField(blank=True, null=True)),
                ('anio_2004', models.IntegerField(blank=True, null=True)),
                ('anio_2005', models.IntegerField(blank=True, null=True)),
                ('anio_2006', models.IntegerField(blank=True, null=True)),
                ('anio_2007', models.IntegerField(blank=True, null=True)),
                ('anio_2008', models.IntegerField(blank=True, null=True)),
                ('anio_2009', models.IntegerField(blank=True, null=True)),
                ('anio_2010', models.IntegerField(blank=True, null=True)),
                ('anio_2011', models.IntegerField(blank=True, null=True)),
                ('anio_2012', models.IntegerField(blank=True, null=True)),
                ('anio_2013', models.IntegerField(blank=True, null=True)),
                ('anio_2014', models.IntegerField(blank=True, null=True)),
                ('anio_2015', models.IntegerField(blank=True, null=True)),
                ('anio_2016', models.IntegerField(blank=True, null=True)),
                ('anio_2017', models.IntegerField(blank=True, null=True)),
                ('anio_2018', models.IntegerField(blank=True, null=True)),
                ('anio_2019', models.IntegerField(blank=True, null=True)),
                ('anio_2020', models.IntegerField(blank=True, null=True)),
                ('anio_2021', models.IntegerField(blank=True, null=True)),
                ('anio_2022', models.IntegerField(blank=True, null=True)),
                ('anio_2023', models.IntegerField(blank=True, null=True)),
                ('anio_2024', models.IntegerField(blank=True, null=True)),
                ('anio_2025', models.IntegerField(blank=True, null=True)),
                ('anio_2026', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
