# Generated by Django 6.1 on 2026-08-24 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_modelo', '0002_remove_modelo_id_modelo_idmodelo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelo',
            name='anio_2000',
        ),
        migrations.RemoveField(
            model_name='modelo',
            name='anio_2001',
        ),
        migrations.RemoveField(
            model_name='modelo',
            name='anio_2002',
        ),
        migrations.RemoveField(
            model_name='modelo',
            name='anio_2003',
        ),
        migrations.RemoveField(
            model_name='modelo',
            name='anio_2004',
        ),
        migrations.RemoveField(
            model_name='modelo',
            name='anio_2005',
        ),
        migrations.RemoveField(
            model_name='modelo',
            name='anio_2006',
        ),
        migrations.RemoveField(
            model_name='modelo',
            name='anio_2007',
        ),
        migrations.RemoveField(
            model_name='modelo',
            name='anio_2008',
        ),
        migrations.RemoveField(
            model_name='modelo',
            name='anio_2009',
        ),
        migrations.RemoveField(
            model_name='modelo',
            name='anio_2010',
        ),
        migrations.RemoveField(
            model_name='modelo',
            name='anio_2011',
        ),
        migrations.RemoveField(
            model_name='modelo',
            name='anio_2012',
        ),
        migrations.RemoveField(
            model_name='modelo',
            name='anio_2013',
        ),
        migrations.RemoveField(
            model_name='modelo',
            name='anio_2014',
        ),
        migrations.RemoveField(
            model_name='modelo',
            name='anio_2015',
        ),
        migrations.RemoveField(
            model_name='modelo',
            name='anio_2016',
        ),
        migrations.RemoveField(
            model_name='modelo',
            name='anio_2017',
        ),
        migrations.RemoveField(
            model_name='modelo',
            name='anio_2018',
        ),
        migrations.RemoveField(
            model_name='modelo',
            name='anio_2019',
        ),
        migrations.RemoveField(
            model_name='modelo',
            name='anio_2020',
        ),
        migrations.RemoveField(
            model_name='modelo',
            name='anio_2021',
        ),
        migrations.RemoveField(
            model_name='modelo',
            name='anio_2022',
        ),
        migrations.RemoveField(
            model_name='modelo',
            name='anio_2023',
        ),
        migrations.RemoveField(
            model_name='modelo',
            name='anio_2024',
        ),
        migrations.RemoveField(
            model_name='modelo',
            name='anio_2025',
        ),
        migrations.RemoveField(
            model_name='modelo',
            name='anio_2026',
        ),
        migrations.AddField(
            model_name='modelo',
            name='Nombre_Modelo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
