# Generated by Django 6.1 on 2026-08-24 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_modelo', '0003_remove_modelo_anio_2000_remove_modelo_anio_2001_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelo',
            name='Año',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='modelo',
            name='Color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='modelo',
            name='Marca',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='modelo',
            name='Placa',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
