# Generated by Django 6.1 on 2026-08-24 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repartidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombres', models.CharField(blank=True, max_length=255, null=True)),
                ('Apellidos', models.CharField(blank=True, max_length=255, null=True)),
                ('Nro_Identificacion', models.CharField(blank=True, max_length=255, null=True)),
                ('Telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('Observacion_Rechazo', models.TextField(blank=True, null=True)),
                ('Fecha_Validacion', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
