# Generated by Django 6.1 on 2026-08-24 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_repartidor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repartidor',
            name='id',
        ),
        migrations.AddField(
            model_name='repartidor',
            name='idRepartidor',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
