# Generated by Django 6.1 on 2026-08-24 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_repartidor', '0002_remove_repartidor_id_repartidor_idrepartidor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repartidor',
            name='Fecha_Validacion',
        ),
        migrations.AddField(
            model_name='repartidor',
            name='Estado',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='repartidor',
            name='Apellidos',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='repartidor',
            name='Nombres',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='repartidor',
            name='Nro_Identificacion',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
