# Generated by Django 6.1 on 2026-08-28 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pagos_repartidor',
            fields=[
                ('id_pagos', models.AutoField(primary_key=True, serialize=False)),
                ('id_Repartidor', models.IntegerField(db_column='id_Repartidor')),
                ('monto_total_generado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('comision_plataforma', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monto_neto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('fallido', 'Fallido')], default='pendiente', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Seguimiento_Geolocalizacion',
            fields=[
                ('id_Seguimiento', models.AutoField(primary_key=True, serialize=False)),
                ('id_Repartidor', models.IntegerField(db_column='id_Repartidor')),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('velocidad', models.IntegerField()),
            ],
        ),
    ]
