# Generated by Django 6.1 on 2026-08-28 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id_colores', models.AutoField(db_column='idColores', primary_key=True, serialize=False)),
                ('rojo', models.PositiveIntegerField(db_column='Rojo', default=0)),
                ('amarillo', models.PositiveIntegerField(db_column='Amarillo', default=0)),
                ('verde', models.PositiveIntegerField(db_column='Verde', default=0)),
                ('negro', models.PositiveIntegerField(db_column='Negro', default=0)),
            ],
            options={
                'verbose_name': 'Color',
                'verbose_name_plural': 'Colores',
                'db_table': 'Colores',
                'ordering': ['id_colores'],
            },
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id_modelo', models.AutoField(db_column='idModelo', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=100)),
            ],
            options={
                'verbose_name': 'Modelo',
                'verbose_name_plural': 'Modelos',
                'db_table': 'Modelo',
            },
        ),
        migrations.CreateModel(
            name='Repartidor',
            fields=[
                ('id_repartidor', models.BigAutoField(db_column='idRepartidor', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=150)),
            ],
            options={
                'verbose_name': 'Repartidor',
                'verbose_name_plural': 'Repartidores',
                'db_table': 'Repartidor',
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id_vehiculo', models.BigAutoField(db_column='idVehiculo', primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('MOTO', 'Moto'), ('CARRO', 'Carro'), ('CAMIONETA', 'Camioneta'), ('FURGON', 'Furgón'), ('OTRO', 'Otro')], db_column='Tipo', max_length=20)),
                ('marca', models.CharField(db_column='Marca', max_length=100)),
                ('linea', models.CharField(db_column='Linea', max_length=100)),
                ('placa', models.CharField(db_column='Placa', max_length=20, unique=True)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('RECHAZADO', 'Rechazado'), ('PENDIENTE', 'Pendiente')], db_column='Estado', max_length=20)),
                ('observacion_rechazo', models.TextField(blank=True, db_column='Observacion_Rechazo', null=True)),
                ('activo', models.BooleanField(db_column='Activo', default=True)),
                ('fecha_validacion', models.DateTimeField(blank=True, db_column='Fecha_Validacion', null=True)),
                ('color', models.ForeignKey(db_column='Colores_idColores', on_delete=django.db.models.deletion.PROTECT, related_name='vehiculos', to='app_vehiculos_colores.color')),
                ('modelo', models.ForeignKey(db_column='Modelo_idModelo', on_delete=django.db.models.deletion.PROTECT, related_name='vehiculos', to='app_vehiculos_colores.modelo')),
                ('repartidor', models.ForeignKey(db_column='Repartidor_idRepartidor', on_delete=django.db.models.deletion.PROTECT, related_name='vehiculos', to='app_vehiculos_colores.repartidor')),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
                'db_table': 'Vehiculo',
                'ordering': ['-id_vehiculo'],
            },
        ),
    ]
