# Generated by Django 6.0.8 on 2026-08-25 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contraseña', models.CharField(max_length=128)),
                ('rol', models.CharField(choices=[('admin', 'Admin'), ('cliente', 'Cliente'), ('repartidor', 'Repartidor')], max_length=50)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(max_length=100)),
                ('url_archivo', models.CharField(max_length=200)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('vigente', 'Vigente'), ('expirado', 'Expirado')], max_length=20)),
                ('empresa_id', models.BigIntegerField(blank=True, null=True)),
                ('repartidor_id', models.BigIntegerField(blank=True, null=True)),
                ('entidad_tipo', models.CharField(choices=[('empresa', 'Empresa'), ('repartidor', 'Repartidor')], max_length=50)),
                ('entidad_id', models.BigIntegerField(blank=True, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_usuario_documento.usuario')),
            ],
        ),
    ]
