# Generated by Django 6.0.8 on 2026-08-24 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seguimiento_Geolocalizacion',
            fields=[
                ('id_Seguimiento', models.AutoField(primary_key=True, serialize=False)),
                ('id_Repartidor', models.IntegerField(db_column='id_Repartidor')),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('velocidad', models.IntegerField()),
            ],
        ),
    ]
