# Generated by Django 6.1 on 2026-08-24 15:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('idEmpresa', models.BigAutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=200)),
                ('Nit', models.CharField(max_length=50, unique=True)),
                ('Direccion', models.CharField(max_length=300)),
                ('Telefono_contacto', models.CharField(max_length=20)),
                ('Representante_legal_nombre', models.CharField(max_length=200)),
                ('Representante_legal_telefono', models.CharField(max_length=20)),
                ('Representante_legal_correo', models.EmailField(max_length=225)),
                ('Tipo_colaboracion', models.CharField(choices=[('SOCIO', 'Socio Comercial'), ('PROVEEDOR', 'Proveedor'), ('ALIADO', 'Aliado Estratégico')], max_length=50)),
                ('Estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=50)),
                ('Observacion_rechazo', models.TextField(blank=True, null=True)),
                ('Fecha_validacion', models.DateTimeField(blank=True, null=True)),
                ('Usuario_idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Convenios',
            fields=[
                ('convenio_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('porcentaje_comision', models.DecimalField(decimal_places=2, max_digits=5)),
                ('zonas_cobertura', models.TextField(help_text='Zonas de cobertura')),
                ('condiciones_facturacion', models.TextField()),
                ('fecha_inicion', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_termino', models.DateField(verbose_name='Fecha de Término')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('FINALIZADO', 'Finalizado')], default='ACTIVO', max_length=50)),
                ('Empresa_idEmpresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convenios', to='app_empresa_convenios.empresa', verbose_name='Empresa')),
            ],
        ),
    ]
