# Generated by Django 6.1 on 2026-08-24 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pago_entrega', models.BigIntegerField(blank=True, null=True)),
                ('servicio_id', models.BigIntegerField(blank=True, null=True)),
                ('asignacion_id', models.BigIntegerField(blank=True, null=True)),
                ('nombre_destinatario', models.CharField(max_length=150)),
                ('telefono_destinatario', models.CharField(blank=True, max_length=30)),
                ('direccion', models.CharField(max_length=500)),
                ('latitud', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('prioridad', models.CharField(choices=[('Baja', 'Baja'), ('Media', 'Media'), ('Alta', 'Alta')], default='Media', max_length=10)),
                ('estado_entrega', models.CharField(choices=[('Pendiente', 'Pendiente'), ('En Ruta', 'En Ruta'), ('Entregado', 'Entregado'), ('Cancelado', 'Cancelado')], default='Pendiente', max_length=20)),
                ('firma_digital_url', models.URLField(blank=True, max_length=500)),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa_id', models.BigIntegerField()),
                ('codigo_servicio', models.CharField(max_length=50)),
                ('tipo_envio', models.CharField(blank=True, max_length=100)),
                ('cantidad_entregas', models.PositiveIntegerField(blank=True, null=True)),
                ('direccion_recogidas', models.CharField(max_length=500)),
                ('fecha_deseada', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('Solicitado', 'Solicitado'), ('En Proceso', 'En Proceso'), ('Completado', 'Completado'), ('Cancelado', 'Cancelado')], default='Solicitado', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
            ],
        ),
    ]
