# Generated by Django 6.1 on 2026-08-24 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('asignacion_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('servicios_servicios_id', models.BigIntegerField()),
                ('servicio_id', models.BigIntegerField()),
                ('repartidor_id', models.BigIntegerField()),
                ('fecha_aceptacion', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'asignaciones',
            },
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('idrutas', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo_ruta', models.CharField(max_length=50)),
                ('tiempo_estimado_min', models.IntegerField()),
                ('polyline_json', models.TextField()),
                ('seleccionada', models.BooleanField(default=False)),
                ('asignacion', models.ForeignKey(db_column='Asignaciones_asignacion_id', on_delete=django.db.models.deletion.CASCADE, to='app_rutas_asignaciones.asignacion')),
            ],
            options={
                'db_table': 'rutas',
            },
        ),
    ]
